project:
  type: website

website:
  title: "Ahmad Ilu"

  navbar:
    search: true
    back-to-top-navigation: true

    left:
      - text: "Home"
        href: index
      - text: "About"
        href: about
      - text: "Publications"
        href: publications
      - text: "Data"
        href: data
      - text: "Codes"
        href: codes

    right:
      - text: "CV"
        href: files/Ahmad_Ibraheem_Ilu_CV.pdf
        icon: file-earmark-person

      - icon: twitter
        href: "https://x.com/IluAhmad_"

      - icon: github
        menu:
          - text: "Source Code"
            href: "https://github.com/Iluahmad/Academic-Profile"
          - text: "Report a Bug"
            href: "https://github.com/Iluahmad"

  page-footer:
    left: "© 2024 Ahmad Ilu"
    right:
      - icon: github
        href: "https://github.com/Iluahmad"
      - icon: twitter
        href: "https://x.com/IluAhmad_"

format:
  html:
    theme: pulse
    toc: true
    smooth-scroll: true