project:
  type: website
  output-dir: docs


website:
  title: "Iluahmad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Publications.qmd
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



