navbar:
  search: true
  back-to-top-navigation: true
  page-footer: "Copyright 2024, Ahmad Ilu" 

  left:
    - text: "Home"
      href: index.qmd
    - about.qmd
    - Publications.qmd
    - Data.qmd
    - Codes.qmd

  right:
    - text: "CV"
      href: files/Ahmad_Ibraheem_Ilu_CV.pdf
      icon: file-earmark-person

    - icon: twitter
      href: https://x.com/IluAhmad_
    - icon: github
      menu:
        - text: Source Code
          href: https://github.com/Iluahmad/Academic-Profile
        - text: Report a Bug
          href: https://github.com/Iluahmad
