---
title: "Publications"

links:
  - icon: twitter
    text: "Twitter"
    href: "https://x.com/IluAhmad_"

  - icon: github
    text: "Github"
    href: "https://github.com/Iluahmad"

  - icon: envelope
    text: "Email"
    href: "mailto:iluahmad7@yahoo.com"

editor: visual

markdown:
  wrap: 72
---

## Selected Publications

Here are some of my selected publications:

1.  **Geospatial Beamer**\
    [Download PDF](Beamer-Geospatial.pdf)\
    *Presented August, 2024*

2.  **Inflation Flashnotes**\
    [Download PDF](Inflation%20Flash%20note.pdf)

3.  **Unraveling the Price Puzzle**\
    [Download PDF](Unraveling%20the%20Price%20Puzzle.pdf)\
    *Presented June, 2024*

4.  **Energy Subsidy Model**\
    [Download PDF](Energy%20Subsidy.pdf)\
    *Presented October, 2024*

5.  **The Nigerian Economy In 2025 And Beyond**\
    [Download PDF](Economic Report 2024.pdf "The Nigerian Economy In 2025 And Beyond")\
    Economic Report, Office of the Vice President, Federal Republic of Nigeria\
    *Published December, 2024*

6.  **Nigeria Tax Reform - Theory of Change**\
    [Download PDF](Nigerian_Tax_Reform_ToC_2025%20-%20Ahmad%20Ilu.pdf)\
    *Presented July, 2025*

7.  **Nowcasting Framework - Nigeria's GDP**\
    [Download PDF](Nigeria_Macro_Diagnostics.pdf)

    *Presented May, 2026*

8.  **Policy Inclusion and Advocacy Lab**\
    [Download PDF](Policy Inclusion and Advocacy Lab.pdf)

    *Presented August, 2026*