project:
  type: website
  output-dir: docs


website:
  title: "Iluahmad"
  navbar:
    back-to-top-navigation: true
    page-footer: "Copyright 2024, Ahmad Ilu" 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Publications.qmd
        text: Publications
      - href: Data.qmd
        text: Data 
      - href: Codes.qmd
        text: Codes and Charts
    tools:
      - icon: twitter
        href: https://x.com/IluAhmad_
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Iluahmad/Academic-Profile
          - text: Report a Bug
            href:  https://github.com/Iluahmad
        
 
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



